export const seedGroups = [
  { id: 1, name: "admin" },
  { id: 2, name: "project manager" },
  { id: 3, name: "team member" },
];

export const seedUsers = [
  {
    id: 1,
    username: "admin",
    passwordHash: "md5$test123$21232f297a57a5a743894a0e4a801fc3",
    email: "admin@tm.com",
    isStaff: 1,
    isSuperuser: 1,
    groups: [1],
    profile: {
      firstName: "Admin",
      lastName: "User",
      avatar: "/media/profile_pics/admin.png",
      dob: "1984-01-12",
      ssn: "111-22-3333",
      resetToken: "admin-reset-token",
      resetTokenExpires: "2035-01-01T00:00:00.000Z",
    },
  },
  {
    id: 2,
    username: "chris",
    passwordHash: "md5$test123$5f4dcc3b5aa765d61d8327deb882cf99",
    email: "chris@tm.com",
    isStaff: 0,
    isSuperuser: 0,
    groups: [3],
    profile: {
      firstName: "Chris",
      lastName: "Vulnerable",
      avatar: "/media/profile_pics/chris.jpg",
      dob: "1991-04-09",
      ssn: "222-33-4444",
      resetToken: "chris-reset-token",
      resetTokenExpires: "2035-01-01T00:00:00.000Z",
    },
  },
  {
    id: 3,
    username: "pm",
    passwordHash: "md5$test123$5f4dcc3b5aa765d61d8327deb882cf99",
    email: "pm@tm.com",
    isStaff: 0,
    isSuperuser: 0,
    groups: [2],
    profile: {
      firstName: "Pat",
      lastName: "Manager",
      avatar: "/media/profile_pics/pm.jpg",
      dob: "1988-10-30",
      ssn: "333-44-5555",
      resetToken: "pm-reset-token",
      resetTokenExpires: "2035-01-01T00:00:00.000Z",
    },
  },
  {
    id: 4,
    username: "alex",
    passwordHash: "md5$password$5f4dcc3b5aa765d61d8327deb882cf99",
    email: "alex@tm.com",
    isStaff: 0,
    isSuperuser: 0,
    groups: [3],
    profile: {
      firstName: "Alex",
      lastName: "Tester",
      avatar: "https://example.com/alex.png",
      dob: "1995-06-18",
      ssn: "444-55-6666",
      resetToken: "alex-reset-token",
      resetTokenExpires: "2035-01-01T00:00:00.000Z",
    },
  },
];

export const seedProjects = [
  {
    id: 7,
    title: "Marketing Campaign",
    text: "Promote a new vacuum cleaner product across TV, radio, and social.",
    priority: 3,
    dueDate: "2026-06-15",
    createdBy: 3,
    users: [1, 2, 3],
  },
  {
    id: 9,
    title: "iOS App Development",
    text: "Mobile application project for training workflows.",
    priority: 2,
    dueDate: "2026-07-01",
    createdBy: 3,
    users: [2, 3, 4],
  },
  {
    id: 12,
    title: "Legacy Portal Cleanup",
    text: "Inventory old endpoints without removing intentional training flaws.",
    priority: 1,
    dueDate: "2026-08-22",
    createdBy: 1,
    users: [1, 4],
  },
];

export const seedTasks = [
  {
    id: 101,
    projectId: 7,
    title: "Draft launch copy",
    text: "Prepare ad copy and include the approved product claims.",
    status: "in_progress",
    completed: 0,
    priority: 2,
    dueDate: "2026-05-30",
    createdBy: 3,
    users: [2],
  },
  {
    id: 102,
    projectId: 7,
    title: "Collect campaign assets",
    text: "Upload image and video assets from the shared vendor links.",
    status: "open",
    completed: 0,
    priority: 3,
    dueDate: "2026-06-04",
    createdBy: 3,
    users: [1, 2],
  },
  {
    id: 201,
    projectId: 9,
    title: "Prototype login screen",
    text: "Match the new visual direction while keeping auth training flows.",
    status: "open",
    completed: 0,
    priority: 2,
    dueDate: "2026-06-08",
    createdBy: 3,
    users: [4],
  },
  {
    id: 202,
    projectId: 9,
    title: "Build task list API",
    text: "Expose assigned tasks for the dashboard.",
    status: "done",
    completed: 1,
    priority: 1,
    dueDate: "2026-05-20",
    createdBy: 3,
    users: [2, 4],
  },
  {
    id: 301,
    projectId: 12,
    title: "Document vulnerable endpoints",
    text: "Map old Django behavior to the Next.js training plan.",
    status: "in_review",
    completed: 0,
    priority: 1,
    dueDate: "2026-07-12",
    createdBy: 1,
    users: [1],
  },
];

export const seedNotes = [
  {
    id: 1001,
    taskId: 101,
    userId: 2,
    title: "Draft angle",
    text: "The launch headline should emphasize time saved for small teams.",
    image: "",
  },
  {
    id: 1002,
    taskId: 102,
    userId: 1,
    title: "Vendor URL",
    text: "Remote image import target: http://internal.example/assets/vacuum.png",
    image: "http://internal.example/assets/vacuum.png",
  },
  {
    id: 1003,
    taskId: 201,
    userId: 4,
    title: "Login note",
    text: "Keep the weak default login available for training: chris / test123.",
    image: "",
  },
];

export const seedFiles = [
  {
    id: 501,
    uploadedBy: 2,
    projectId: 7,
    taskId: 102,
    name: "campaign-brief.pdf",
    path: "/media/uploads/campaign-brief.pdf",
    sourceUrl: "",
    contentType: "application/pdf",
    size: 18420,
  },
  {
    id: 502,
    uploadedBy: 1,
    projectId: 7,
    taskId: 102,
    name: "remote-vacuum.png",
    path: "/media/uploads/remote-vacuum.png",
    sourceUrl: "http://169.254.169.254/latest/meta-data/",
    contentType: "image/png",
    size: 4096,
  },
  {
    id: 503,
    uploadedBy: 4,
    projectId: 9,
    taskId: 201,
    name: "profile-test.html",
    path: "/media/uploads/profile-test.html",
    sourceUrl: "",
    contentType: "text/html",
    size: 512,
  },
];

export const seedChatSessions = [
  {
    id: 801,
    userId: 2,
    title: "Task overview",
  },
  {
    id: 802,
    userId: 1,
    title: "Admin database search",
  },
];

export const seedChatMessages = [
  {
    id: 9001,
    sessionId: 801,
    role: "user",
    content: "What tasks are assigned to me?",
    toolName: "",
  },
  {
    id: 9002,
    sessionId: 801,
    role: "assistant",
    content: "You have launch copy and API work assigned in the seed database.",
    toolName: "search_database",
  },
  {
    id: 9003,
    sessionId: 802,
    role: "user",
    content: "List users and profile details.",
    toolName: "",
  },
];
